### ISSUE TITLE
Does it decompose polygons with holes?

### ISSUE THREAD

**Issue by pentacular** [schteppe/poly-decomp.js#10]

**Comment by schteppe** [comment]
No, it doesn't.

**Comment by finscn** [comment]
@pentacular  , I found poly-decomp.js support the polygon with holes.
But you must connect all holes to outer border  with bridges. 
like this
![image](https://user-images.githubusercontent.com/288367/57205281-211e9f80-6ff0-11e9-9f97-67c78c05bf08.png)

So we just need a util function to help us to create hole bridge .

I'm working on it .
When it's done , I will create a PR for this repo (I hope this is not a dead project)

**Comment by finscn** [comment]
![image](https://user-images.githubusercontent.com/288367/57328215-630c2a80-7143-11e9-8875-0bd7d0044364.png)

I hope I could finish it in the next few days.

I need more testing.

**Comment by dattn** [comment]
@finscn 
Did you found a solution for that ?
Or is there a other library for this feature i could use ?
