### ISSUE TITLE
clockwise order info

### ISSUE THREAD

**Issue by sdrabb** [schteppe/poly-decomp.js#3]
hi thank's for you're great library i've got a question:
before decomposing a polygon in convex area  i need to be sure that the points are in counter clockwise order using makeCCW () ?

and another questione: your decomp() function use that  https://mpen.ca/406/keil it's true?

**Comment by schteppe** [comment]
Good question. Does it work if you skip the makeCCW step?

Yes, decomp() is the Keil algorithm and and quickDecomp() is the Bayazit one.

**Comment by schteppe** [comment]
Update: Yes, the polygon needs to be in counter-clockwise order.
