### ISSUE TITLE
Could support a polygon with some holes ?

### ISSUE THREAD

**Issue by finscn** [schteppe/poly-decomp.js#7]
I want to use this repo to decomp  a polygon with some holes , 

Could support  it ?

Thanks

**Comment by finscn** [comment]
@schteppe  could you tell me ? thanks

**Comment by schteppe** [comment]
If you have a shape with a hole in it, usually you can make a line connecting the hole with the outer edge, making it a single concave polygon. Does that help?

**Comment by finscn** [comment]
@schteppe  , Thanks.

 Another question , the algorithm of this project is faster than earcut ?

**Comment by schteppe** [comment]
@finscn Earcut is a triangulation library and this library does convex decomposition. Different problems and different solutions. I don’t think you can compare them.

**Comment by finscn** [comment]
Thanks.
